### ISSUE TITLE
🔧 项目维护-希望接入清华的chatGLM

### ISSUE THREAD

**Issue by Angelyeye** [ConnectAI-E/Feishu-OpenAI#104]
# 项目维护问题和建议 🔧

欢迎在此分享您对项目维护的问题和建议，我们期待听到您的想法和建议。

## 您的问题或建议是什么？ 🤔

希望能接入清华的开源模型ChatGLM，从商业化和数据安全角度来说，开源模型chatGLM会比openai的ChatGPT好不少，后续加入的飞书文档相关功能也需要考虑数据安全性，而且chatGLM可以自己训练，可以和飞书结合更好

ChatGML官网：https://chatglm.cn/blog

ChatGML GitHub：https://github.com/THUDM/ChatGLM-6B

**Comment by Leizhenpeng** [comment]
https://github.com/ConnectAI-E/Feishu-ChatGLM

已经完成
