### ISSUE TITLE
🐞 消息中如果带列表，机器人会罢工

### ISSUE THREAD

**Issue by licstar** [ConnectAI-E/Feishu-OpenAI#156]
# 错误报告 🐞

<img width="82" alt="image" src="https://user-images.githubusercontent.com/3314022/228528358-52983850-9733-4fd3-be9d-05e98babb78e.png">
发送这种带记号的消息，机器人会罢工。报错信息为：
error getting message type: unknown message type: post

**Comment by LufeiCheng** [comment]
该错误与[#184]一致，将会在最近修复
