### ISSUE TITLE
🚀 功能改善 - 更精准的tokenizer切割判断

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/Feishu-OpenAI#162]
# 功能改善建议 🚀

欢迎在此分享您对功能的改善建议，我们期待听到您的想法和建议。

现在的处理是借助字符串长度来判断是否超过最大token，
根据openai官方的tokenizer，https://platform.openai.com/tokenizer
显然这种做法并不合理，需要优化这种判断

## 您的建议是什么？ 🤔

利用[goja](https://github.com/dop251/goja)来运行openai官方的[tokenizer](https://github.com/latitudegames/GPT-3-Encoder)
可以参考：
https://github.com/pandodao/tokenizer-go

感谢您的分享和支持！🙏

**Comment by LufeiCheng** [comment]
请问这个功能目前在进行中了吗，如果目前没有commiter来完成这项工作，我可以尝试引入tokenizer-go包，来完成它

**Comment by Leizhenpeng** [comment]
欢迎PR！！！！我最近太忙了。。。愁。。。
