### ISSUE TITLE
我看了一圈，没看懂你这个代码在整个即时通信，是哪个环节

### ISSUE THREAD

**Issue by pigping88** [ConnectAI-E/Feishu-OpenAI#186]
我对飞书不了解，我看了一圈，没看懂你这个代码在整个即时通信，是哪个环节，你这个是搭建私有即时通讯？还是只接入gpt，桌面端代码呢，还是飞书公用的桌面程序

**Comment by toeasy** [comment]
这是基于飞书的机器人搭建的，需要先理解如何玩转飞书机器人
