### ISSUE TITLE
🚀 功能改善：飞书中的消息回复是否支持流式输出？

### ISSUE THREAD

**Issue by chswy123** [ConnectAI-E/Feishu-OpenAI#188]
# 功能改善建议 🚀

飞书中的消息回复是否支持流式输出？目前使用是体验是必须等待全部文本整体返回。

## 您的建议是什么？ 🤔

能否支持流式输出？类似chatGPT官网回复那样

**Comment by LufeiCheng** [comment]
https://github.com/ConnectAI-E/Feishu-OpenAI-Stream-Chatbot

作者的另一个仓库，已经支持了该功能，可以体验看看

**Comment by chswy123** [comment]
> https://github.com/ConnectAI-E/Feishu-OpenAI-Stream-Chatbot
> 
> 作者的另一个仓库，已经支持了该功能，可以体验看看

感谢！

**Comment by liusuxian** [comment]
@LufeiCheng 这个流失的方式老是超时失败，不知道什么原因
