### ISSUE TITLE
🐞 错误报告 语音发送bug

### ISSUE THREAD

**Issue by yingshang** [ConnectAI-E/Feishu-OpenAI#191]
# 错误报告 🐞

如果您在使用此项目时遇到了错误，请在此报告，我们会尽快解决此问题。

## 错误描述 🤔

发送语音会报错，但是在服务器上面会发现MP3文件，猜测是解析MP3报错

## 附加信息 📝

![image](https://user-images.githubusercontent.com/11006249/231750528-c6a1eed1-bee2-4154-a730-5be7e9c943d3.png)
![image](https://user-images.githubusercontent.com/11006249/231750666-623f0741-40f9-41d3-b1ad-f4929cb7ac54.png)

**Comment by Leizhenpeng** [comment]
建议使用飞书自己的SDK来实现语音识别，而不是调用whisper。因为目前whisper在安卓设备上可能存在兼容性问题。

**Comment by yingshang** [comment]
OK，我重写下代码

**Comment by Xyy-tj** [comment]
请问这个问题最后有解决吗，我也遇到了，一样是有MP3，报错信息也相同
