### ISSUE TITLE
🚰 部署问题反馈

### ISSUE THREAD

**Issue by dishangyijiao** [ConnectAI-E/Feishu-OpenAI#192]
# 问题交流 💬

在阿里云Serverless部署遇到了问题

## 问题描述 🤔
在阿里云-中国香港，通过Serverless进行部署，发送消息时，会返回如下报错，发送卡片消息正常。
```go
2023-04-14 10:19:112023/04/14 02:19:10 [Error] [handle event,path:/webhook/event,error:event type: message, not found handler]
[GIN] 2023/04/14 - 02:19:10 | 200 |     215.645µs |   123.58.10.238 | POST     "/webhook/event"
2023/04/14 02:19:10 [Error] [handle event,path:/webhook/event, error:runtime error: invalid memory address or nil pointer dereference]
[GIN] 2023/04/14 - 02:19:10 | 500 |     871.631µs |   123.58.10.239 | POST     "/webhook/event"
2023-04-14 10:19:26
```
在railsway上部署的是正常的，看到这个issue[错误报告-goroutine异步任务，返回空nil指针，导致进程崩溃](https://github.com/ConnectAI-E/Feishu-OpenAI/issues/178)已经修复了问题，但还会遇到同样的问题。

对Go还不是很熟悉，我尝试本地debug下。

## 附加信息 📝

为了更好地了解您遇到的问题，我们需要您提供以下信息：
- 输出日志
  - 报错日志 [1-6438bf25-2167f34368ea46fba077bd4b.log](https://github.com/ConnectAI-E/Feishu-OpenAI/files/11228408/1-6438bf25-2167f34368ea46fba077bd4b.log)
- 操作系统、Go 版本等环境信息。
  - 操作系统 Linux Debian 9
  - Go 1.20.1

感谢您的反馈和支持！🙏

**Comment by sgch1982** [comment]
本地部署，也碰到了这个问题

**Comment by sgch1982** [comment]
把

> 本地部署，也碰到了这个问题

把配置文件里的代理配置了一下，解决了这个问题

**Comment by dishangyijiao** [comment]
- 遇到的问题解决了，主要是copy`config.example.yaml`文件的时候，由于使用的OpenAI的key，文件中的`AZURE_ON`需要设为`false`。
