### ISSUE TITLE
🚀 功能改善

### ISSUE THREAD

**Issue by toeasy** [ConnectAI-E/Feishu-OpenAI#198]
# 功能改善建议 🚀

欢迎在此分享您对功能的改善建议，我们期待听到您的想法和建议。

## 您的建议是什么？ 🤔

想在代码中引入日志，增加DEBUG日志，方便调试，部署后日志级别调整为INFO

 

感谢您的分享和支持！🙏

**Comment by Leizhenpeng** [comment]
感谢贡献，非常实用的功能~
