### ISSUE TITLE
🚰 部署问题反馈

### ISSUE THREAD

**Issue by Ethan-Zhang** [ConnectAI-E/Feishu-OpenAI#200]
# 问题交流 💬

在腾讯云虚拟机上部署失败

## 问题描述 🤔

尝试了新加坡地域和巴西圣保罗地域都不能正常访问openai，显示IP被ban

如下**43.135.214.239**是巴西地域虚拟机分配的公网IP，请问国内其他云如阿里云可以部署吗？或者我需要使用国外的如aws？

Access denied

You do not have access to chat.openai.com.

The site owner may have set restrictions that prevent you from accessing the site.

  • Ray ID: 7b9a20adcd34a5b6
  • Timestamp: 2023-04-18 04:22:36 UTC
  • Your IP address: 43.135.214.239
  • Requested URL: chat.openai.com/
  • Error reference number: 1020
  • Server ID: FL_487F52
  • User-Agent: w3m/0.5.3+git20210102

## 附加信息 📝

为了更好地了解您遇到的问题，我们需要您提供以下信息：

- 输出日志，包括错误信息和堆栈跟踪。
- 相关的代码片段或文件。
- 操作系统、golang 版本等环境信息。

感谢您的反馈和支持！🙏

**Comment by LufeiCheng** [comment]
aws香港是可以访问openai的

另外，也可以尝试注册下azure的openai服务，这个国内目前可以访问

**Comment by Leizhenpeng** [comment]
阿里云和railway已经凉了，如果你是公司用户，可以尝试体验我们推出的商业交付版 https://connect-ai.forkway.cn/
