### ISSUE TITLE
🚰 部署问题反馈

### ISSUE THREAD

**Issue by princemero** [ConnectAI-E/Feishu-OpenAI#203]
# 问题交流 💬

使用railway app一键部署，之前使用都很正常， 今天突然发现飞书接受不到消息了，请问有可能是遇到了什么问题？
.
## 问题描述 🤔
https://xxxxxxxx.railway.app/ping 是通的返回"pong"
尝试重新部署，但还是无法解决。
尝试重置openai  api key 也无法解决
重新部署后请求地址，超时3秒

## 附加信息 📝

railway app deloy logs：
2023/04/21 01:55:45 http server started: http://localhost:9000/webhook/event
[GIN] 2023/04/21 - 01:55:46 | 200 |      86.106µs |     10.10.10.12 | GET      "/ping"

感谢您的反馈和支持！🙏

**Comment by shnoarisu** [comment]
今天发现也是用不了

**Comment by Ethan-Zhang** [comment]
同样的问题，不知道是不是地域太远，还是说飞书把railway封禁了，我也写了个issue，希望能增加检测机制 #207

**Comment by princemero** [comment]
在群友的帮助下，现已基本解决了这个问题，现在分享我的解决方法，以帮助同样使用railway进行部署的小伙伴们。首先，你可能会遇到超时或机器人无法回复的问题，这很可能是因为railway已被墙。为了解决这个问题，你可以在railway后台添加子域名，并使用CloudFlare CDN将域名链接填入飞书后台的请求地址处（原railway生成的域名链接已被墙：https://xxxxxxxx.railway.app）
![1682084801320](https://user-images.githubusercontent.com/52058661/233652287-1056cab3-29df-4ad8-93c2-eaab77fcf040.jpg)
注意：如果您使用了CloudFlare，请在SSL/TLS处设置完整或更高。

**Comment by princemero** [comment]
> 今天发现也是用不了
已解决~看我评论
