### ISSUE TITLE
🚰 部署问题反馈: railway webhook/event 和 webhook/card 请求超时

### ISSUE THREAD

**Issue by wenqi73** [ConnectAI-E/Feishu-OpenAI#204]
# 问题交流 💬

使用 railway 一键部署，之前运行很好，4月20号机器人无法工作。应该和 #203 是一个问题。

## 问题描述 🤔
ping 没问题。`webhook/event` 和 `webhook/card` 在飞书页面配置时请求超时

**Comment by Leizhenpeng** [comment]
哈哈，如果你们公司使用，可以试试我们推出的商业交付版 https://connect-ai.forkway.cn/

**Comment by princemero** [comment]
已解决，可看链接：https://github.com/ConnectAI-E/Feishu-OpenAI/issues/203#issue-1677601566
