### ISSUE TITLE
🚀 使用stream接口和飞书的卡片，实现打字机效果

### ISSUE THREAD

**Issue by licstar** [ConnectAI-E/Feishu-OpenAI#206]
模仿chatgpt网页版的功能，实现一点点出答案的效果。对于大段的代码，或者gpt4的请求，体验提升或非常明显。
openai的python sdk自带流式回复的功能，应该用go也可以

飞书的卡片消息可以更新内容，有望实现这一效果
https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/patch

**Comment by Leizhenpeng** [comment]
https://github.com/ConnectAI-E/Feishu-OpenAI-Stream-Chatbot 早已实现拉

**Comment by licstar** [comment]
太赞了！话说为什么要分两个项目呢
