### ISSUE TITLE
🚀 功能改善 能不能换掉卡片消息，手机端不能复制卡片消息

### ISSUE THREAD

**Issue by SKDDJ** [ConnectAI-E/Feishu-OpenAI#214]
# 功能改善建议 🚀

欢迎在此分享您对功能的改善建议，我们期待听到您的想法和建议。

## 您的建议是什么？ 🤔

能不能换掉机器人第一条回复的卡片消息，手机端不能复制卡片消息

**Comment by SKDDJ** [comment]
把/code/handlers/文件下面的event_action_msg.go还是叫什么来着的文件中的if(msg==0)那个判断条件中的函数从sendnewcard换成replymsg函数就好了

**Comment by wenqi73** [comment]
@Leizhenpeng 这里可以考虑加个复制按钮？
