### ISSUE TITLE
🚰 部署问题反馈

### ISSUE THREAD

**Issue by lzqlzzq** [ConnectAI-E/Feishu-OpenAI#216]
# 问题交流 💬

部署在阿里云函数上，频繁出现`[Error] [handle event,path:/webhook/event,error:event type: message, not found handler]`与`Error: Invocation canceled by client (duration: 3815ms, maxMemoryUsage: 0.00MB)`报错。
飞书后台日志没有任何报错：
![image](https://user-images.githubusercontent.com/79011287/235976327-6dbc3795-d501-4210-ba81-6d5e2a259549.png)
大部分情况会无法使用，有时可正常使用（简单的单轮对话）。

## 附加信息 📝
以下有为飞书上配置的事件：
![image](https://user-images.githubusercontent.com/79011287/235975303-707e4565-f8db-4309-9dcf-2a8ba2972299.png)
以下为配置的权限，应当已经包含需要的权限：
![image](https://user-images.githubusercontent.com/79011287/235975631-5220a39a-f5e0-422c-a2e0-03b93533c36c.png)
![image](https://user-images.githubusercontent.com/79011287/235975725-899ea51b-406f-4da1-9612-eeaddd57c5e6.png)
![image](https://user-images.githubusercontent.com/79011287/235975781-0125e448-1ed0-4b6a-ade1-c13defaaa876.png)
以下为阿里云函数后台的典型报错与记录：
![image](https://user-images.githubusercontent.com/79011287/235977109-98e749b3-c07f-4374-b9c8-f6d57a605929.png)
![image](https://user-images.githubusercontent.com/79011287/235977164-fb9fa45d-3f9c-4299-8bb8-3b2cbc15b6e0.png)
![image](https://user-images.githubusercontent.com/79011287/235977205-0e87f148-dfe6-43c0-be88-8b03f807ec3b.png)

**Comment by wujianguo** [comment]
https://github.com/ConnectAI-E/Feishu-OpenAI/issues/126

**Comment by lzqlzzq** [comment]
> #126

已修复，感谢～
