### ISSUE TITLE
🐞 错误报告  重试逻辑报错

### ISSUE THREAD

**Issue by LufeiCheng** [ConnectAI-E/Feishu-OpenAI#218]
# 错误报告 🐞

在使用的过程中，收到【🤖️：消息机器人摆烂了，请稍后再试～\n错误信息: openai请求失败】，经过日志排查，发现重试逻辑的问题

## 错误描述 🤔

![img_v2_b2a141b8-36a6-4bb2-af38-2ee4c755a5eg](https://user-images.githubusercontent.com/37326655/236611057-456a7404-e2e5-4829-b920-f6c631c6f5f4.jpg)

在使用的过程中，发生上述错误，经过排查，定位到相关日志

![image](https://user-images.githubusercontent.com/37326655/236611165-09433d79-2551-4286-bf88-297ede6eb1bc.png)

发现在第一次请求openai失败后，之后的重试请求，均返回400  Bad Request
查询代码后发现，在重试时，执行了下述代码
```go
response, err = client.Do(req)
```
在net/http包中，req的Body是一个ioReader，服务端在读取时，对应的offset会后移，如果直接使用req重试，服务端会读取不到请求体的内容，进而导致Bad Request

**Comment by Leizhenpeng** [comment]
感谢！
