### ISSUE TITLE
🐞 错误报告 invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by yigubigu** [ConnectAI-E/Feishu-OpenAI#235]
# 错误报告 🐞

如果您在使用此项目时遇到了错误，请在此报告，我们会尽快解决此问题。

## 错误描述 🤔

已经配置好飞书和azure openai，发送请求时候，始终报错
feishu-chatgpt  | 2023/06/10 04:28:52 [Error] [handle event,path:/webhook/event, error:runtime error: invalid memory address or nil pointer dereference]

## 附加信息 📝

请提供以下信息以帮助我们更快地解决问题：

- feishu-chatgpt  | 2023/06/10 04:28:52 [Error] [handle event,path:/webhook/event, error:runtime error: invalid memory address or nil pointer dereference]

- 相关的代码片段或文件
- mac 

感谢您的反馈！🙏

**Comment by QingsiLiu** [comment]
应该是网络请求的问题吧，可以检查一下你部署的服务器是不是无法和OpenAI正常通信。我在US网络下可以正常提供服务，但是在国内的本地服务器不行

**Comment by Chting** [comment]
> 应该是网络请求的问题吧，可以检查一下你部署的服务器是不是无法和OpenAI正常通信。我在US网络下可以正常提供服务，但是在国内的本地服务器不行

应该不是网络问题，我用微软云服务器，微软云open Ai 也会这样

**Comment by lonelyke123** [comment]
请问这个问题解决了吗？排除网络问题

**Comment by 283859691** [comment]
这个有没有进展啊

**Comment by Leizhenpeng** [comment]
部署服务器和openai连接性有问题

**Comment by QingsiLiu** [comment]
> 

debug一下就知道啦，确实是网络请求的问题，client.Do()那里

**Comment by lonelyke123** [comment]
我们再检查下，你们要是能正常使用理论上我们部署也应该能用

**Comment by 283859691** [comment]
我们使用的是azure，也是报这个错误
