### ISSUE TITLE
卡片不能交互![image](https://user-images.githubusercontent.com/30498168/228862577-8259a1ec-03c3-462f-af41-f755b4b76c2f.png)

### ISSUE THREAD

**Issue by DigYang** [ConnectAI-E/Feishu-OpenAI#252]
![image](https://user-images.githubusercontent.com/30498168/228862577-8259a1ec-03c3-462f-af41-f755b4b76c2f.png)
我点击选项卡之后会出错，不能选择，请问是为啥呀

_Originally posted by @zchoi in https://github.com/ConnectAI-E/Feishu-OpenAI/issues/136#issuecomment-1490371108_

**Comment by Leizhenpeng** [comment]
没有配置消息卡片的回调~

**Comment by WenHowe** [comment]
> 没有配置消息卡片的回调~

lark 6.10.10，代理lark.com / larksuite.com / 自定义域名
配置了，选择的时候还是会报错(但能成功触发)，如下
<img width="669" alt="iShot_2023-08-14_16 40 17" src="https://github.com/ConnectAI-E/Feishu-OpenAI/assets/6345591/6743d7b6-3e90-4d9a-a5ad-af4606d12371">

card callback url
![iShot_2023-08-14_16 41 10](https://github.com/ConnectAI-E/Feishu-OpenAI/assets/6345591/b77a3998-865f-48df-b651-90782e59f0e5)
