### ISSUE TITLE
🐞 错误报告 使用流式对话和Azure的API（gpt4）报错

### ISSUE THREAD

**Issue by anerus** [ConnectAI-E/Feishu-OpenAI#257]
# 错误报告 🐞

使用流式对话和Azure的API（gpt4）报错

## 错误描述 🤔

开启流式对话和azure的api报错，关闭流式对话可正常对话
![screenshot-20230712-132156](https://github.com/ConnectAI-E/Feishu-OpenAI/assets/39954581/71c3908c-9516-4ce9-85a4-eb95f078cec7)

## 附加信息 📝

请提供以下信息以帮助我们更快地解决问题：

- 输出日志，包括错误信息和堆栈跟踪
- [GIN] 2023/07/12 - 13:14:59 | 200 |   43.736071ms |   123.58.10.238 | POST     "/webhook/event"
2023/07/12 13:14:59 [Debug] [req:PATCH,/open-apis/im/v1/messages/:message_id]
2023/07/12 13:15:00 [Debug] [req:PATCH,/open-apis/im/v1/messages/:message_id]
2023/07/12 13:15:01 [Debug] [req:PATCH,/open-apis/im/v1/messages/:message_id]
2023/07/12 13:15:02 [Debug] [req:PATCH,/open-apis/im/v1/messages/:message_id]
2023/07/12 13:15:02 [Debug] [req:PATCH,/open-apis/im/v1/messages/:message_id]
2023/07/12 13:15:03 [Debug] [req:PATCH,/open-apis/im/v1/messages/:message_id]
2023/07/12 13:15:04 [Debug] [req:PATCH,/open-apis/im/v1/messages/:message_id]
2023/07/12 13:15:04 [Debug] [req:PATCH,/open-apis/im/v1/messages/:message_id]
2023/07/12 13:15:05 [Debug] [req:PATCH,/open-apis/im/v1/messages/:message_id]
2023/07/12 13:15:05 no content timeout
2023/07/12 13:15:05 [Debug] [req:PATCH,/open-apis/im/v1/messages/:message_id]
2023/07/12 13:15:05 [Debug] [req:PATCH,/open-apis/im/v1/messages/:message_id]
2023/07/12 13:15:09 
2023/07/12 13:15:09 
[GIN] 2023/07/12 - 13:15:09 | 200 | 14.072390263s |   123.58.10.238 | POST     "/webhook/event"
response:  {chatcmpl-7bMTffgnnvR6y7FDausxemve8vTRI chat.completion.chunk 1689138895 gpt-4 [{0 { assistant <nil>} }]}
2023/07/12 13:15:11 [Debug] [req:PATCH,/open-apis/im/v1/messages/:message_id]
- 相关的代码片段或文件
- 您的操作系统、软件版本等环境信息

感谢您的反馈！🙏

**Comment by Leizhenpeng** [comment]
已解决~
